### ISSUE TITLE
Pypi version 1.07 is old, like 2020

### ISSUE THREAD

**Issue by ddmee** [h2non/filetype.py#107]
I'm trying to guess a file type that is .mp3. The latest release is version 1.07. That's also the version available on pypi. However, the mp3 I am guessing is one that isn't recognised by 1.07. However, on github's master, the mp3 version is now recognised.

Why is the repo going so long between making releases? The 1.07 was released in 2020. There's been improvements since then. It seems like you need to make more frequency releases.

Have you lost access to the pypi repo or something?

**Comment by h2non** [comment]
Version `1.0.8` is now available on PyPI: https://pypi.org/project/filetype/

**Comment by ddmee** [comment]
Cheers that's great
