### ISSUE TITLE
Anyway to add a custom type (with magic bytes) ?

### ISSUE THREAD

**Issue by martinm1000** [h2non/filetype.py#110]
The readme says there is, but I can't find anything. I need to add custom types to the library. Is is possible ? Can I somehow inject my own Type Classes ?

**Comment by h2non** [comment]
Use [`filetype.add_type(customer_matcher)`](https://github.com/h2non/filetype.py/blob/master/filetype/filetype.py#L85)

**Comment by martinm1000** [comment]
Thank you it worked !
