### ISSUE TITLE
xlsx file guess error

### ISSUE THREAD

**Issue by Mr-xn** [h2non/filetype.py#138]
the xlsx guess to zip file :
<img width="280" alt="image" src="https://user-images.githubusercontent.com/18260135/185645593-300fe223-46ac-4b47-8031-f1652e3a0041.png">

the file :
[test_filetype.xlsx](https://github.com/h2non/filetype.py/files/9383051/test_filetype.xlsx)

**Comment by ferstar** [comment]
@Mr-xn fixed in: https://github.com/h2non/filetype.py/pull/137

waiting for @h2non pushing the latest code to [pypi](https://pypi.org/project/filetype/#history) :)

**Comment by Mr-xn** [comment]
cool！thanks your work !
