### ISSUE TITLE
Does not recognize mp3 type

### ISSUE THREAD

**Issue by MikhailMurashov** [h2non/filetype.py#139]
Hi! I have mp3 file what does not recognize by filetype. [Link to file](https://cloud.mail.ru/public/Mm2X/cNDSeJBnr)
First three bytes in my file: `0xff 0xfa 0xe3`
I have tried to use [python-magic](https://github.com/ahupp/python-magic) and it recognized this file like `audio/mpeg`. Can you look into it please?

**Comment by guigarfr** [comment]
You have the errors in the logs, just fix them and update the PR.

```
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:46:5: E129 visually indented line with same indent as next logical line
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:47:21: E117 over-indented
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:55:5: E129 visually indented line with same indent as next logical line
/home/runner/work/filetype.py/filetype.py/filetype/types/audio.py:56:25: E117 over-indented
```
