### ISSUE TITLE
xls and xlsx guessed as zip

### ISSUE THREAD

**Issue by mjturtora** [h2non/filetype.py#142]
I thought this might be related to the open office fix just committed so I tried v0.1.3 and same issue. Originally tried v1.0.0

I got it to work on some image and video file types but confounds xls* with zip.

Oddly, it claims the file extension is zip as well. I get:

File extension: zip
File MIME type: application/zip

I haven't dug into this codebase enough to know how it tries to do it but it seems to be reading the magic numbers. There is an old Microsoft support response that may be useful but mainly because it says how hard this problem is:

[Developing a tool to recognise MS Office file types ( .doc, .xls, .mdb, .ppt )](https://social.msdn.microsoft.com/Forums/en-US/343d09e3-5fdf-4b4a-9fa6-8ccb37a35930/developing-a-tool-to-recognise-ms-office-file-types-doc-xls-mdb-ppt-?forum=os_binaryfile)

**Comment by LifeforDream** [comment]
Got the same problem here.

It seems like _.document_ types are not yet in pypi distibution.
Current version is [1.1.0](https://pypi.org/project/filetype/1.1.0/), uploaded on 12 Jul - https://github.com/h2non/filetype.py/commit/47a0e25934a229f6a8be340541250014d5baa60d

PR with documents #133 got merged 5 Aug.

So, unless you are building from source, there is no support for .xls* in filetype yet.

**Comment by muhmudrik** [comment]
Hi, sorry to mention @h2non 
Is there any estimation when the newest version will be up?

**Comment by ferstar** [comment]
@mjturtora @LifeforDream @muhmudrik v1.2.0 now available: https://pypi.org/project/filetype

**Comment by muhmudrik** [comment]
Thank you very much! @ferstar

**Comment by h2non** [comment]
This should be good. Closing.
