### ISSUE TITLE
pip install filetype doesn't work: ImportError: No module named filetype

### ISSUE THREAD

**Issue by francesco1119** [h2non/filetype.py#17]
Your code is great and it's helping me so much. 
BTW I have to flag you a problem: `pip install filetype` doesn't work and your test code keep repeating:

```
Traceback (most recent call last):
  File "TestFiletype.py", line 4, in <module>
    import filetype
ImportError: No module named filetype
```
even if `filetype `is correclty installed:
![correctlyinstalled](https://user-images.githubusercontent.com/3397477/33800093-80b0de94-dd9e-11e7-9ada-6e6dff0cfa59.PNG)
So I had to download your setup.py file but it wasn't installing because `'README.rst'` was missing:
![missinginstall](https://user-images.githubusercontent.com/3397477/33800099-afe38eaa-dd9e-11e7-8677-c4c39877ce44.PNG)
...really, do I need `'README.rst'` in order to install your repository? 
So I downloaded the complete .zip and `filetype `installed correctly and now everything works.

arriving to install filetype through `pip install filetype` would be amazing

Thank you to keep up the good code

**Comment by ztane** [comment]
Your Python is 2.7, yet you're using the `pip` from 3.5! A module is not installable with *only* setup.py, hence this is all invalid. Use [`python -mpip`](https://stackoverflow.com/a/35899129/918959] to run the `pip` that is linked to whatever the `python` command is pointing to.

**Comment by Jadamoureen** [comment]
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    from rave import rave_python,raveExceptions, Misc
ModuleNotFoundError: No module named 'rave'

**Comment by dosas** [comment]
@h2non Can we close this?
