### ISSUE TITLE
Support SVG images

### ISSUE THREAD

**Issue by andrewmfiorillo** [h2non/filetype.py#38]
Hi!

We have a use case to detect images including SVG. This library is perfect except for missing the SVG format. I'm happy to make a PR in the next few days if that's alright.

Edit with sample: https://upload.wikimedia.org/wikipedia/commons/0/02/SVG_logo.svg

**Comment by h2non** [comment]
This library is exclusively intended for binary archives. 

SVG file detecting requires a fundamentally different approach to detect not based in the header magic bytes, such as a fine-grained regular expression matching.

You can port this implementation to Python:
https://github.com/h2non/go-is-svg

**Comment by andrewmfiorillo** [comment]
Works for me, thanks!
