### ISSUE TITLE
detecting mp4 video

### ISSUE THREAD

**Issue by leocov-dev** [h2non/filetype.py#40]
I have an mp4 video that returns on a call to _get_ftyp() like so:
```
('isom', 1, ['isom', 'avc1', 'mp42'])
```
Should the matching be more lenient for 'compatible brands'?  I'm asking because I don't know what `isom` is and its unclear what the intention is with parsing out compatible brands.

**Comment by lin-evil** [comment]
I'm having an issue with detecting .mp4 files too. This is what I get from _get_ftype():
major brand:
isom
minor version:
512
compatible brands:
['isom', 'iso2', 'avc1', 'mp41']

**Comment by leocov-dev** [comment]
This library is well thought out, so in my project I ended up adding a type matcher like this:
```
class Mp4Compatible(video.Mp4):
    """
    More lenient mp4 detection
    """
    def match(self, buf):
        if not self._is_isobmff(buf):
            return False

        major_brand, minor_version, compatible_brands = self._get_ftyp(buf)
        return any([cb in ['mp41', 'mp42'] for cb in compatible_brands])

filetype.add_type(Mp4Compatible())
```
But it would be nice to have more insight into the decisions and inner workings of the library.

**Comment by lucidBrot** [comment]
@leocov-dev Sounds nice! But I'm not understanding where you add this. Did you modify this library's source code in your cloned version, or is it possible to add this modification when I got the library through pip?

Copy pasting your code and using `from filetype import *` gives me `AttributeError: 'function' object has no attribute 'Mp4'`

**Comment by fgsalomon** [comment]
> @leocov-dev Sounds nice! But I'm not understanding where you add this. Did you modify this library's source code in your cloned version, or is it possible to add this modification when I got the library through pip?
> 
> Copy pasting your code and using `from filetype import *` gives me `AttributeError: 'function' object has no attribute 'Mp4'`

I guess that you already fixed that by now but anyways this worked for me:

```python
from filetype.types import video
```

I wonder why @leocov-dev more lenient matcher is not added to the library.

**Comment by dosas** [comment]
So can we close this then?
