### ISSUE TITLE
Any way to feed .guess() with bytes instead of a file ?

### ISSUE THREAD

**Issue by remort** [h2non/filetype.py#42]
To be able to check file content in form data receiving from front end.

**Comment by h2non** [comment]
You can pass a string, byte or bytearray:
https://github.com/h2non/filetype.py/blob/master/filetype/match.py#L19-L20

**Comment by AlekseiMarinichenko** [comment]
> You can pass a string, byte or bytearray:
> https://github.com/h2non/filetype.py/blob/master/filetype/match.py#L19-L20

To be clear in the terminology: you can pass a PATH TO FILE, byte or bytearray.

**Comment by dosas** [comment]
@remort Can we close this?

**Comment by remort** [comment]
@dosas looks like it receives bytes, yes. We can close it. Thank you.

**Comment by dosas** [comment]
@remort I think you have the permissions to close it? Because I don't :(
