### ISSUE TITLE
support svg

### ISSUE THREAD

**Issue by viponedream** [h2non/filetype.py#48]
it doesn't support svg format.
how can i do?
many are svg format now.
you have a go lang version, but how to use in python?

**Comment by h2non** [comment]
You can port the Go code into Python. It's basically a regex test.

**Comment by HansBambel** [comment]
For others that also want to check for svg it worked for me using this code snippet (from https://github.com/h2non/go-is-svg):

```
def svg_match(file) -> str | None:
    """Return the mime-type of svg when the file matches a SVG regex."""
    content = file.read().decode()
    replaced = re.sub(r"(?i)<!--([\\s\\S]*?)-->", "", content)
    found_match = re.search(
        r"(?i)^\s*(?:<\?xml[^>]*>\s*)?(?:<!doctype svg[^>]*>\s*)?<svg[^>]*>[^*]*<\/svg>\s*$", replaced
    )
    if found_match:
        return "image/svg+xml"
    return None
```
