### ISSUE TITLE
Licensing for tests/fixtures/*

### ISSUE THREAD

**Issue by eribertomota** [h2non/filetype.py#67]
Hi @h2non,

I am trying put filetype.py in Debian. However, the tests/fixtures/* files seems are not originally developed by you and the Debian FTP Masters rejected the package. I can see it, in sample.jpg:

Copyright (c) 1998 Hewlett-Packard Company

Please, can you clarify?

I suggest you generate all files and put a specific notice about it.

Regards,

Eriberto

**Comment by h2non** [comment]
Can't you simply ignore the file or the `tests/` directory?

**Comment by eribertomota** [comment]
I can always repack your tarball to remove the files because they are non-free and can't be uploaded to Debian. For Debian, 1.0.7 version will be 1.0.7+dfsg (files excluded; non compliant with DFSG[1]). 

[1] https://www.debian.org/social_contract#guidelines

**Comment by h2non** [comment]
`sample.jpg` was replaced with a copyright-free image on `master`. I hope that works!

**Comment by eribertomota** [comment]
Can you add a README or LICENSING file inside directory confirming all files are copyrighted by you using the same license of filetype? I need this to declare the copyright notice inside debian/copyright, as required Debian format 1.0[1].

[1] https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

**Comment by h2non** [comment]
Happy to merge a PR with the required changes.

**Comment by eribertomota** [comment]
Thanks. Sent #68. Feel free to change the commit.
